# -*- coding: utf-8 -*-
"""Crime Analysis in San Francisco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XUJPed6x89Hf-2pS5Ajl5Lh7IUIHE6N

##Importing the required libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
!pip install squarify
import squarify
import warnings
warnings.filterwarnings('ignore')

"""##Download the data set"""

df=pd.read_csv("Police_Department_Incidents_Previous_Year_2016.csv", engine='python')

df.head()

df.describe()

"""##Check if there are any null values"""

df.isnull().sum()

"""##Different categories of crime"""

plt.rcParams['figure.figsize'] = (30, 19)
plt.style.use('dark_background')

sns.countplot(df['Category'], palette = 'gnuplot')

plt.title('Major Crimes in Sanfrancisco', fontweight = 30, fontsize = 20)
plt.xticks(rotation =90)
plt.show()

"""##Plotting a tree map"""

y = df['Category'].value_counts().head(25)

plt.rcParams['figure.figsize'] = (15, 15)
plt.style.use('fivethirtyeight')

color = plt.cm.magma(np.linspace(0, 1, 15))
squarify.plot(sizes = y.values, label = y.index, alpha=.8, color = color)
plt.title('Tree Map for Top 25 Crimes', fontsize = 20)

plt.axis('off')
plt.show()

"""##Description of the Crime"""

from wordcloud import WordCloud

plt.rcParams['figure.figsize'] = (15, 15)
plt.style.use('fast')

wc = WordCloud(background_color = 'orange', width = 1500, height = 1500).generate(str(df['Descript']))
plt.title('Description of the Crime', fontsize = 20)

plt.imshow(wc)
plt.axis('off')
plt.show()

"""##Regions with count of crimes"""

plt.rcParams['figure.figsize'] = (20, 9)
# You can see available styles using plt.style.available
# For example, 'seaborn-v0_8-darkgrid' or 'fivethirtyeight'
# plt.style.use('seaborn') # This line caused the error
plt.style.use('ggplot') # Using a valid style as an example

color = plt.cm.spring(np.linspace(0, 1, 15))
df['PdDistrict'].value_counts().plot.bar(color = color, figsize = (15, 10))

plt.title('District with Most Crime',fontsize = 30)

plt.xticks(rotation = 90)
plt.show()

"""##Top 15 Addresses in San Francisco in Crime"""

plt.rcParams['figure.figsize'] = (20, 9)
plt.style.use('ggplot') # Changed from 'seaborn' to 'ggplot'

color = plt.cm.ocean(np.linspace(0, 1, 15))
df['Address'].value_counts().head(15).plot.bar(color = color, figsize = (15, 10))

plt.title('Top 15 Regions in Crime',fontsize = 20)

plt.xticks(rotation = 90)
plt.show()

"""##Regions with days of crimes"""

plt.style.use('ggplot')

# Get the value counts for DayOfWeek
day_counts = df['DayOfWeek'].value_counts()

# Create an explode tuple with the correct length
explode_tuple = [0.1] * len(day_counts)

# Plot the pie chart
ax = day_counts.plot.pie(
    figsize=(15, 8),
    explode=explode_tuple,
    autopct='%1.1f%%',     # percentage on slices
    labels=None,           # hide labels on slices
    shadow=True,
    startangle=90
)

# Add legend to show which color belongs to which day
plt.legend(
    day_counts.index,
    title="Day of Week",
    loc="center left",
    bbox_to_anchor=(1, 0.5)
)

plt.title('Crime count on each day', fontsize=20)
plt.ylabel('')
plt.show()

"""##Crimes in Each Month"""

df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month

plt.style.use('fivethirtyeight')
plt.rcParams['figure.figsize'] = (15, 8)

sns.countplot(x='Month', data=df, palette='autumn')

plt.title('Crimes in Each Month', fontsize=20)
plt.show()

"""##Checking the time at which crime occurs mostly"""

color = plt.cm.twilight(np.linspace(0, 5, 100))
df['Time'].value_counts().head(20).plot.bar(color = color, figsize = (15, 9))

plt.title('Distribution of crime over the day', fontsize = 20)
plt.show()

"""##District vs Category of Crime"""

data = pd.crosstab(df['Category'], df['PdDistrict'])
color = plt.cm.Greys(np.linspace(0, 1, 10))

data.div(data.sum(1).astype(float), axis = 0).plot.bar(stacked = True, color = color, figsize = (18, 12))
plt.title('District vs Category of Crime', fontweight = 30, fontsize = 20)

plt.xticks(rotation = 90)
plt.show()

"""##Geographical Visualization"""

t = df.PdDistrict.value_counts()

table = pd.DataFrame(data=t.values, index=t.index, columns=['Count'])
table = table.reindex(["CENTRAL", "NORTHERN", "PARK", "SOUTHERN", "MISSION", "TENDERLOIN", "RICHMOND", "TARAVAL", "INGLESIDE", "BAYVIEW"])

table = table.reset_index()
table.rename({'index': 'Neighborhood'}, axis='columns', inplace=True)

table

"""##Density of crime in San Francisco"""

gjson = r'https://cocl.us/sanfran_geojson'
sf_map = folium.Map(location = [37.77, -122.42], zoom_start = 12)

#generate map
folium.Choropleth(
    geo_data=gjson,
    data=table,
    columns=['PdDistrict', 'Count'], # Changed 'Neighborhood' to 'PdDistrict'
    key_on='feature.properties.DISTRICT',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Crime Rate in San Francisco'
).add_to(sf_map)

sf_map

